app:
  name: diamond-bot
  services:
    - name: diamond-bot-service
      type: web
      env:
        - name: NODE_ENV
          value: production
        - name: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
          value: "true"
      instance:
        type: nano
      ports:
        - port: 3000
          protocol: http
      health_checks:
        - http:
            path: /
            port: 3000
      routes:
        - path: /
          port: 3000
      build:
        type: buildpack
        builder: heroku/buildpacks:20
